POST http://localhost:3001/connect/login
Content-Type: application/json

{
    "password": "naman123",
    "username": "mailsender"
}

###
GET http://localhost:3001/connect/dummy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYxNTM2MTcxOH0.u60q2WwIkJ8jBRCzPfyZqL2O5udzVOiMaE7X_DxDQ9w